// This file was autogenerated by calcdeps.py
goog.addDependency("../../../../../../home/cpeisert/repos cdp/closure-ant-tasks/test/test_projects/unit_testing/demo.js", ['demo'], ['goog.format.JsonPrettyPrinter']);
goog.addDependency("../../../../../../home/cpeisert/repos cdp/closure-ant-tasks/test/test_projects/unit_testing/demo-deps.js", [], []);
goog.addDependency("../../../../../../home/cpeisert/repos cdp/closure-ant-tasks/test/test_projects/unit_testing/demo_test.js", [], ['demo', 'goog.testing.jsunit']);
